# Generated by Django 6.0.2 on 2026-02-18 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='fa-circle-dot', max_length=60, verbose_name='Icône FA')),
                ('color_class', models.CharField(default='ci-divers', max_length=40, verbose_name='Classe CSS')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Montant')),
                ('type', models.CharField(choices=[('expense', 'Dépense'), ('income', 'Revenu'), ('planned_expense', 'Dépense planifiée'), ('planned_income', 'Revenu attendu')], default='expense', max_length=20, verbose_name='Type')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('source', models.CharField(choices=[('manual', 'Saisie manuelle'), ('sms', 'SMS Mobile Money'), ('ai', 'Extrait par IA')], default='manual', max_length=10, verbose_name='Source')),
                ('raw_sms', models.TextField(blank=True, verbose_name='SMS original')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Limite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_limits', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.category')),
            ],
            options={
                'verbose_name': 'Limite budgétaire',
                'unique_together': {('user', 'category')},
            },
        ),
    ]
