# Generated by Django 6.0.2 on 2026-02-19 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrimoineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype', models.CharField(choices=[('actif', 'Actif'), ('passif', 'Passif')], max_length=10, verbose_name='Type')),
                ('category', models.CharField(choices=[('immobilier', 'Immobilier'), ('business', 'Business / Entreprise'), ('epargne', 'Épargne / Liquidités'), ('investissement', 'Investissement (BVMAC)'), ('vehicule', 'Véhicule'), ('dette', 'Dette / Emprunt'), ('credit', 'Crédit'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Catégorie')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
                ('valeur', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Valeur (FCFA)')),
                ('date', models.DateField(verbose_name="Date d'évaluation")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimoine', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrée patrimoine',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
